@serviceUrl = http://localhost:4004/odata/v4/test-data

# @serviceUrl = https://msgsystemsag-06-tum-praktika-shd-tdd-invalnos-data-generator.cfapps.eu10-004.hana.ondemand.com/odata/v4/test-data

### Get InsuranceContracts
GET {{serviceUrl}}/InsuranceContract

### Get ContractDetails
GET {{serviceUrl}}/ContractDetails

### Get Emails
GET {{serviceUrl}}/Emails

### Generate Data
POST {{serviceUrl}}/generateData
content-type: application/json

{
    "contractCount" : 900,
    "contractCreationYearRange" : 40,
    "activeContractDist" : 0.6,
    "lowerBoundContractDetailsCount" : 10,
    "upperBoundContractDetailsCount" : 20,
    "reportingDuration" : 20,
    "allowedDelay" : 20,
    "neutralContractsProb" : 0.2,
    "nonPenalizedContractsProb" : 0.8,
    "lowerBoundReportingValueVariance" : 0.6,
    "upperBoundReportingValueVariance" : 2.1,
    "lowerBoundNOP" : -1,
    "upperBoundNOP" : -2,
    "lowerBoundR" : 1,
    "upperBoundR" : 1111,
    "lowerBoundAS" : 111,
    "upperBoundAS" : 1111,
    "lowerBoundVOG" : 1111,
    "upperBoundVOG" : 11111,
    "clientChangesEmailProb" : 0.1
}

### !! CAUTION !! Reset Database by dumping all data
POST {{serviceUrl}}/resetDatabase
content-type: application/json