@serviceUrl = http://localhost:4004/odata/v4/test-data

# @serviceUrl = https://msgsystemsag-06-tum-praktika-shd-tdd-invalnos-data-generator.cfapps.eu10-004.hana.ondemand.com/odata/v4/test-data

### Get InsuranceContracts
GET {{serviceUrl}}/InsuranceContract

### Get ContractDetails
GET {{serviceUrl}}/ContractDetails

### Get Emails
GET {{serviceUrl}}/Emails

### Generate Data
POST {{serviceUrl}}/generateData
content-type: application/json

{
    "contractCount" : 3
}

### !! CAUTION !! Reset Database by dumping all data
POST {{serviceUrl}}/resetDatabase
content-type: application/json

### Generate Data
GET {{serviceUrl}}/generateContracts()